[tool.poetry]
name = "python-scraping"
version = "0.1.0"
description = ""
authors = ["Kevin Rincon <kevinrincon8@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
selenium = "^4.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
